language: cpp
compiler: clang
os: linux
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-9
      - ninja-build
  snaps:
    - tidy

env:
  global:
    - TEST_REPO=https://github.com/TomTasche/OpenDocument.test.git
    - CORE_DIR=$TRAVIS_BUILD_DIR
    - TEST_DIR=$TRAVIS_BUILD_DIR/../OpenDocument.test
    - TOOL_DIR=$HOME/tools
    - TRANSLATION_TOOL=$TOOL_DIR/translate.py
    - BUILD_LATEST=$HOME/build-latest
    - BUILD_REFERENCE=$HOME/build-reference
    - OUTPUT_LATEST=$HOME/output-latest
    - OUTPUT_REFERENCE=$HOME/output-reference

cache:
  ccache: true
  directories:
    - $TEST_DIR

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - |
    if [ ! -d $TEST_DIR ] || [ -z "$(ls -A $TEST_DIR)"]; then
      git clone $TEST_REPO $TEST_DIR
    else
      git -C $TEST_DIR pull
    fi

script:
  # copy tools
  - cp -a $CORE_DIR/.travis $TOOL_DIR

  # build latest
  - mkdir -p $BUILD_LATEST
  - cd $BUILD_LATEST; cmake -GNinja $CORE_DIR
  - cmake --build .

  # run unit tests
  - $BUILD_LATEST/test/odr_test

  # run latest translation
  - mkdir -p $OUTPUT_LATEST
  - $TRANSLATION_TOOL $BUILD_LATEST/cli/translate $OUTPUT_LATEST $TEST_DIR/od?/* $TEST_DIR/???x/*

  # build reference
  - cd $CORE_DIR; git checkout $CORE_REF
  - mkdir -p $BUILD_REFERENCE
  - cd $BUILD_REFERENCE; cmake -GNinja $CORE_DIR
  - cmake --build .

  # run reference translation
  - mkdir -p $OUTPUT_REFERENCE
  - $TRANSLATION_TOOL $BUILD_REFERENCE/cli/translate $OUTPUT_REFERENCE $TEST_DIR/od?/* $TEST_DIR/???x/*

  # compare output directories
  - tidy -i -m -w 160 -ashtml -utf8 $OUTPUT_LATEST/*.html 2> /dev/null || true # TODO remove null and true
  - tidy -i -m -w 160 -ashtml -utf8 $OUTPUT_REFERENCE/*.html 2> /dev/null || true # TODO remove null and true
  - diff $OUTPUT_LATEST $OUTPUT_REFERENCE
