sudo: false

language: cpp

git:
  depth: 10

addons:
  apt:
    packages:
      - ninja-build

compiler:
  - clang
  - gcc

cache:
  - ccache

install:
  - wget https://raw.githubusercontent.com/andiwand/gdrive.sh/master/gdrive.sh -O gdrive.sh

script:
  - mkdir -p build && cd build && cmake -GNinja .. && cmake --build . && cd ..
  - cd test && bash ../gdrive.sh "${INPUT}" && [[ -d "input/" ]] && cd ..
  - cd test && bash ../gdrive.sh "${OUTPUT}" && [[ -d "output/" ]] && cd ..
  - cd test && ODR="../build/main/translate" INPUT_DIR="input" ./translate.sh
