name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: mkdir -p build && cd build && cmake ..
      - name: make
        run: cd build && cmake --build .
