name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-20.04, arch: x86_64, cc: clang, cxx: clang++}
          - { os: macos-10.15, arch: x86_64, cc: clang, cxx: clang++}

    steps:
      - name: ubuntu install ccache
        if: startsWith(matrix.config.os, 'ubuntu')
        run: sudo apt install ccache
      - name: macos install ccache
        if: startsWith(matrix.config.os, 'macos')
        run: brew install ccache

      - name: checkout
        uses: actions/checkout@v2

      - name: ccache
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          key: ${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.compiler }}-rev2

      - name: cmake
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: make
        run: |
          cd build
          cmake --build . -- -j4

      - name: test
        working-directory: build/test
        run: ./odr_test
