name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64]
        compiler: [clang]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ubuntu install ccache
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install ccache
      - name: macos install ccache
        if: startsWith(matrix.os, 'macos')
        run: brew install ccache

      - name: ccache
        uses: actions/cache@v1
        with:
          path: ~/.ccache
          key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}

      - name: cmake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..
      - name: make
        run: cd build && cmake --build .

      - name: test
        run: build/test/odr_test

      - name: install
        run: |
          mkdir -p install
          cd build
          cmake --build . --target install
          cp cli/meta ../install
          cp cli/translate ../install
          cp cli/back_translate ../install

      - name: upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: install
