name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: mkdir -p build && cd build && cmake ..
      - name: make
        run: cd build && cmake --build .
