name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: creat build directroy
        run: mkdir -p build && cd build
      - name: cmake
        run: cmake ..
      - name: make
        run: make -j8
