name: Remote Dispatch Action Initiator

on:
  pull_request:
  repository_dispatch:

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: marcelblanarik/OpenDocument.test
          event-type: trigger-test
          client-payload: '{"ref": "${{ github.ref }}"}'
